# meta/main.yml
galaxy_info:
  author: nida
  description: Ansible role for prometheus installation
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - dir
dependencies: []
